language: python
python:
  - 3.9
install:
  - pip install pipenv -q -pipenv codecov
  - pipenv synnc --dev
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov

codecov:
  token: a054a633-cc8f-4eb3-a32f-8fdeeaaa639a