language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov

codecov:
  token: a054a633-cc8f-4eb3-a32f-8fdeeaaa639a